### ISSUE TITLE
Point your browser to /setup on your local Unmark domain E.g. unmark.local/setup

### ISSUE THREAD

**Issue by Lostapp** [cdevroe/unmark#220]
Hi, 
I don't have a '/setup' dir in my folder?
So I can't setup unmark......
Hope you can help me out :-)

Cheers,
Ries

**Comment by hkockerbeck** [comment]
Unmark is using [CodeIgiter](https://en.wikipedia.org/wiki/CodeIgniter), a web development framework. Frameworks like CodeIgniter (and many others) provide a mechanism called "routes". 

"Routes" take the path part from the URL (like '/setup' or '/marks' or '/labels' or '/mark/edit' and so on) and connect them to the proper code parts. Because of this, the path '/setup' doesn't need to map to an actual folder 'setup', the path '/marks' doesn't need to map to an actual folder 'marks' and so on.

You can find the routes that are defined in Unmark in the file (an actual path this time ;) ) [`/application/config/routes.php`](https://github.com/cdevroe/unmark/blob/master/application/config/routes.php).

**Comment by Lostapp** [comment]
Hi hkockerbeck, 
Thanks for the reply. I'll check it out!
Cheers,
Ries

**Comment by cdevroe** [comment]
@Lostapp Were you able to fix this issue?

**Comment by Lostapp** [comment]
Hi Colin,

Unfortunately not. I finally went on with semantic scuttle……
Thanks for the reply though!

Cheers,
Ries

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Colin Devroe <notifications@github.com>
Verzonden: Friday, June 22, 2018 7:41:11 PM
Aan: cdevroe/unmark
CC: Lostapp; Mention
Onderwerp: Re: [cdevroe/unmark] Point your browser to /setup on your local Unmark domain E.g. unmark.local/setup (#220)


@Lostapp<https://github.com/Lostapp> Were you able to fix this issue?

**Comment by cdevroe** [comment]
This issue can also happen if someone does not have mod_rewrite enabled on PHP. For that, I recommend referencing [this Stack Overflow thread])https://stackoverflow.com/questions/3131236/how-do-you-enable-mod-rewrite-on-any-os).
